version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/Api/Dockerfile

  client:
    image: ${DOCKER_REGISTRY-}client
    build:
      context: .
      dockerfile: src/Client/Dockerfile


  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: src/IdentityServer/Dockerfile

